### ISSUE TITLE
Seren: wrong "Kodi version" and "typo" in tool.py line ~298

### ISSUE THREAD

**Issue by vitorp07** [nixgates/nixgates#1]
```
def closeBusyDialog():
    if int(kodiVersion) > 18: <-----------------------> for Leia(18) it's;  int(kodiVersion) > 17:
        execute('Dialog.Close(busydialognoancel')<----> missing the "c";  busydialognocancel
    else:
execute('Dialog.Close(all,true)')
```

**Comment by doko-desuka** [comment]
Hi @vitorp07, just to help next time, when viewing a source file you can click on a line number to mark it, then hold shift and click on another line number to tag an entire block, then click on the [ . . . ] widget and open a new issue on the selected lines.  
It looks something like this: https://github.com/nixgates/nixgates/blob/1c19edef2d362da62a04c4cd4e1e7e3d61711b9c/plugin.video.Seren/resources/lib/common/tools.py#L299-L300

**Comment by vitorp07** [comment]
Hi @doko-desuka,
Thanks for the reminder, i have absolutely no idea how i forgot about that.
Anyway, great to see @nixgates is back with this awesome project, will help with bugs when possible.

**Comment by nixgates** [comment]
Thanks for catching that out, probably would have never found it. I'll make the changes now.

I've also created a new github repository to handle all Seren related development and keep it separated from the distribution repo. 
You can find it here - https://github.com/nixgates/plugin.video.Seren

Good to see you guys as well :D
