### ISSUE TITLE
Problems with update

### ISSUE THREAD

**Issue by RonM25** [nixgates/nixgates#13]
Last update allowed me to pair with debrid services but no sources found when scraping.  Reinstalled a4kScrapers but still no love.   Shows my trakt account paired successfully when entered but doesn't work when I open Seren.  Using Nvidia Shield TV.

Many thanks for your hard work!

**Comment by holdthatwetblanket** [comment]
Since the update my traktv collection is no longer in alphabetical order.  Also in movie collection I had 340 movies and now it says I only have 94
Thanks!
