### ISSUE TITLE
Not loading shows list or communicating with trakt

### ISSUE THREAD

**Issue by quentin2118** [nixgates/nixgates#15]
Was working fine then suddenly would not load shows or movies lists (like if you click trending etc. It just gives error check log notification will not allow me to verify with tracked or not allow me to use any of the menus as far as trending and things like that

**Comment by drinfernoo** [comment]
Update to 2.0.12, and if issue still persists, open a new issue with a log attached.

**Comment by nixgates** [comment]
Closing this off as theres been no reply for a while. Just as an FYI  if you wouldn't mind putting seren issues on the seren git I'll be able to view more quickly.
