### ISSUE TITLE
Change Request

### ISSUE THREAD

**Issue by newf276** [nixgates/nixgates#16]
I was wondering if you have a plan to swap from syncing with Trakt Collection in order to sync with Trakt Watchlist. I only ask in order to have same common approach as jurialmunkey/plugin.video.themoviedb.helper.

This way, we have both of the best add ons using the same approach. 

Or maybe I am wrong, and Seren does both syncs at the same time, not just with the Trakt Collection!!!

Thank You for the great work you do, please feel free to tell me to bug off :)

**Comment by newf276** [comment]
No response since 29 jan, so I suspect it is not in the cards.  Appreciate all the work you do for us. Thanks

**Comment by pigskins65** [comment]
Try using Nix's Seren git, seems much more active.
