### ISSUE TITLE
Continue Watching shows competed shows

### ISSUE THREAD

**Issue by lukehansford** [nixgates/nixgates#2]
The Continue watching section is displaying fully watched TV shows and Movies

The shows with ticks by them have been fully watched.

Proof

TV Shows

https://ibb.co/ZXGSg30

Movies 

https://ibb.co/b6nFrnr

**Comment by nixgates** [comment]
@lukehansford Continue Watching does not distinguish between completed show or not. All continue watching cares for is if the episode was stopped mid way without completion. 

This is more for a resume from where I was interrupted menu.
