### ISSUE TITLE
Menu list type not conforming when launched fro home shortcut

### ISSUE THREAD

**Issue by decosse** [nixgates/nixgates#5]
From my skin of choice (blackglassnova) I can create shortcuts on the home screen to go directly to one of my trakt lists - in this instance it opens my show list in seren (or can similarly create a separate link to open same list using a different addon)
When opening the shortcut to Seren, the list momentarily displays in my preferred custom list ID view per the Seren settings, however almost immediately reverts to std list. This only happens from the shortcut, if opened from within Seren scrolling down through menus, it opens in custom list and remains as such.
The behaviour is consistent when opening from shortcut - always opens briefly in preferred view and almost immediately switches to std list.
this issue is only prevalent on Seren shortcuts, all other addons open in my preferred list view.

Thanks for all your efforts - much appreciated!

**Comment by decosse** [comment]
Update 
Appears to be a local issue but not sure why ......
Two WIndows 10 machines - same Kodi version (18.1) exhibit this issue - 17.6 did same thing though prior to 18 update
However a third Windows machine does not have the issue - again same config! I had just updated this third machine to todays new Seren release and thought that had fixed it - I had to create the home menu shortcuts on that system as had not been on that machine previously; after I created the shortcuts, it launches perfectly in the custom views.
So thought it was the update - no joy on other two machines though when updated.
Tried uninstalling/deleting Seren completely from the addons and userdata folder (after first wiping anyway from within Seren Tools) - reinstall and still exactly same as original posted error.  
I also have an Android system and it too exhibits the problem.

**Comment by nixgates** [comment]
Apologies for the delay in responding to this issue, generally we keep Seren issues to the plugin.video.seren repository.

Seems with Kodi 18, the changes they have made to the way menus are built/displayed have caused issues downstream to the addons when we try and force a viewtype. An addon can force a view type but there seems be a delay in building of the menu in 18 so it's applied to the previous menu.

Your best bet to 100% get the correct view each time is allow the skin to lock the view type if it's available.

I have added a small delay for the view types that will be applied by Seren but this only a very rough workaround and won't work on all devices.
