### ISSUE TITLE
WatchNixToons

### ISSUE THREAD

**Issue by chewvodka** [nixgates/nixgates#7]
Heya nixgates!

I'm not sure if this is the best way to reach you or not.  I'm not that good with github.  Anyway, I remember troubleshooting the addon "WatchNixToons" with you and somebody else.  I noticed the last couple of days that it's stopped working.  When I select an episode to watch of something, it acts like it tries to connect to the stream but never plays.  I've got a few shows I like to watch every now and then and now they're not working.  I'm not sure if it's all of them, but I tried a couple more random ones and none of them start.  

I thought maybe checking your repo would show that you had a new version I needed to get to address this (I'm using 1.0.3) but it looks like the addon you forked is no longer listed here.  Have you stopped developing your branch of it?  If so, do you know if anybody else has taken up the task of maintaining it, or maybe the original is back to working order? 

If you think you might come back to it, I'd be more than happy to help where I can, giving examples of what I see and logs where I can.  Let me know!

**Comment by nixgates** [comment]
Howdy Chew!

I only ever made a very quick fork of Dandy's project to fix some issues and never really took it on as a full project.

I do believe someone else did take the flame after that and I believe it was called WatchNixToons2? But I'm unsure of who that was.

Sorry I couldn't be more help

**Comment by drinfernoo** [comment]
https://github.com/doko-desuka/plugin.video.watchnixtoons2
