### ISSUE TITLE
Missing cast info.

### ISSUE THREAD

**Issue by warmach1ne23** [nixgates/nixgates#9]
Using Aeon nox silvo not sure if that matters but when I'm watching a movie/series when I hit info I get plot but no cast.

**Comment by drinfernoo** [comment]
What version of Seren are you running? And does the cast info show on other skins, like Estuary? Because if so, this is an issue with your skin, *not* with Seren.

**Comment by warmach1ne23** [comment]
The latest version 1.4.8 it's there for the other addons I use Gaia, scrubs, venom. Tried other skins but they don't seem to have the info screen as they just show plot and that's it.

**Comment by drinfernoo** [comment]
Is this still an issue?
